apiVersion: v1
kind: PersistentVolume
metadata:
  name: telegram-bot-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/pi/telegram-bot-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telegram-bot-pvc
  namespace: telegram-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi