# apiVersion: v1
# kind: Secret
# metadata:
#   name: telegram-bot-secret
#   namespace: telegram-bot
# type: Opaque
# stringData:
#   TOKEN: ""
# Replace "your_bot_token_here" with the actual Telegram bot token