# Secrets should be created locally and never sent to git
apiVersion: v1
kind: Secret
metadata:
  name: telegram-bot-secret
  namespace: bible-quizarium
type: Opaque
stringData:
  TOKEN: "" # Replace this
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: bible-quizarium
  labels:
    app: telegram-leaderboard
type: Opaque
stringData:
  username: "" # Replace this
  password: "" # Replace this
  database: "" # Replace this
